###
GET http://localhost:3000/

# AUTH
### Register
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "username":"kafka",
    "email":"kafka@gmail.com",
    "password":"kafka123",
    "confirmPassword":"kafka123"
}

### Login
POST http://localhost:3000/auth/login
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2Y2E0ZTY0OWM4ZmI0ZDI0MmExMzdkNyIsImVtYWlsIjoia2Fma2FAZ21haWwuY29tIiwiaWF0IjoxNzI0NTM0MzcyfQ.rD7fonKL159CpPK0dSY0MvLXZjhPXPVlfogXS514uXw

{
    "email":"kafka@gmail.com",
    "password":"kafka123"
}

### refresh token
GET http://localhost:3000/auth/refreshToken

#CRUD
### Create
POST http://localhost:3000/note/create
Content-Type: application/json

{
    "title":"Pengeluaran",
    "amount":500000,
    "description":"bayar kos dan makan",
    "date":"12/06/2025",
    "user":1
}

### get notes by id
GET http://localhost:3000/note/1

### get all notes
GET http://localhost:3000/note

### get all notes with pagination
GET http://localhost:3000/notes/paginated?page=1&limit=10

### search
GET http://localhost:3000/notes/search?q=keyword&startDate=2024-01-01&includeArchived=true

### archive notes
PUT http://localhost:3000/notes/archive/1

### unarchive notes
PUT http://localhost:3000/notes/unarchive/1

### get all archived notes with pagination
GET http://localhost:3000/notes/archived?page=1&limit=10

### Update
PUT http://localhost:3000/note/1
Content-Type: application/json

{
    "title":"Pengeluaran",
    "amount":500000,
    "description":"bayar kos, makan dan internet",
    "date":"12/06/2025",
    "user":1
}

### move a note to trash by ID
PUT http://localhost:3000/notes/trash/1

### restore a note from trash by ID (move from trashed to active)
PUT http://localhost:3000/notes/restore/1

### get all notes currently in trash with pagination
GET http://localhost:3000/notes/trashed?page=1&limit=10

### Delete
DELETE http://localhost:3000/note/1